#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Lapce Dark"

[ui]
font-family = ""
font-size = 13
header-height = 28
status-height = 22
activity-width = 40
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
black = "#2B2B2B"
blue = "#6897BB"
cyan = "#629755"
green = "#6A8759"
grey = "#515151"
magenta = "#9876AA"
orange = "#CC7832"
purple = "#9876AA"
red = "#BC3F3C"
white = "#A9B7C6"
yellow = "#FFC66D"

primary-background = "$black"
secondary-background = "#3C3F41"
current-background = "#2E436E"
text = "$white"
dim-text = "#808080"

[color-theme.syntax]
"comment" = "$dim-text"
"constant" = "$blue"
"type" = "$white"
"typeAlias" = "$white"
"number" = "$blue"
"enum" = "$white"
"struct" = "$white"
"structure" = "$white"
"interface" = "$white"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$yellow"
"method" = "$yellow"
"function.method" = "$yellow"
"keyword" = "$orange"
"selfKeyword" = "$orange"
"field" = "$purple"
"property" = "$purple"
"enumMember" = "$purple"
"enum-member" = "$purple"
"string" = "$green"
"type.builtin" = "$orange"
"builtinType" = "$orange"
"escape" = "$orange"
"string.escape" = "$orange"
"embedded" = "$orange"
"punctuation.delimiter" = "$white"
"text.title" = "$yellow"
"text.uri" = "$blue"
"text.reference" = "$yellow"
"variable" = "$white"
"variable.other.member" = "$purple"
"tag" = "$yellow"

"markup.heading" = "$yellow"
"markup.bold" = "$orange"
"markup.italic" = "$orange"
"markup.list" = "$orange"
"markup.link.url" = "$blue"
"markup.link.label" = "$purple"
"markup.link.text" = "$purple"

"bracket.color.1" = "$yellow"
"bracket.color.2" = "$orange"
"bracket.color.3" = "$purple"
"bracket.unpaired" = "$red"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "#D4A017"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#515151"
"lapce.scroll_bar" = "#515151BB"

"lapce.button.primary.background" = "#365880"
"lapce.button.primary.foreground" = "$white"

# tab
"lapce.tab.active.background" = "$primary-background"
"lapce.tab.active.foreground" = "$text"
"lapce.tab.active.underline" = "#4A6DA7"

"lapce.tab.inactive.background" = "$secondary-background"
"lapce.tab.inactive.foreground" = "$dim-text"
"lapce.tab.inactive.underline" = "#4A6DA744"

"lapce.tab.separator" = "#515151"

"lapce.icon.active" = "$text"
"lapce.icon.inactive" = "$dim-text"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$text"
"lapce.plugin.author" = "#B0B0B0"

"editor.background" = "$primary-background"
"editor.foreground" = "$text"
"editor.dim" = "$dim-text"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#BBBBBB"
"editor.selection" = "#214283"
"editor.current_line" = "#323232"
"editor.debug_break_line" = "#2B2B4E"
"editor.link" = "#287BDE"
"editor.visible_whitespace" = "#515151"
"editor.indent_guide" = "#3B3B3B"
"editor.drag_drop_background" = "#214283AA"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$primary-background"

"inlay_hint.foreground" = "$dim-text"
"inlay_hint.background" = "#3C3F4180"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#BC3F3C20"
"error_lens.warning.foreground" = "#D4A017"
"error_lens.warning.background" = "#D4A01720"
"error_lens.other.foreground" = "$dim-text"
"error_lens.other.background" = "#80808020"

"completion_lens.foreground" = "$dim-text"

"source_control.added" = "#629755CC"
"source_control.removed" = "#BC3F3CCC"
"source_control.modified" = "#6897BBCC"

"tooltip.background" = "#3C3F41"
"tooltip.foreground" = "$text"

"palette.background" = "$secondary-background"
"palette.foreground" = "$text"
"palette.current.background" = "$current-background"
"palette.current.foreground" = "$text"

"completion.background" = "$secondary-background"
"completion.current" = "$current-background"

"hover.background" = "$secondary-background"

"activity.background" = "$secondary-background"
"activity.current" = "$primary-background"

"debug.breakpoint" = "#DB5860"
"debug.breakpoint.hover" = "#DB586066"

"panel.background" = "$secondary-background"
"panel.foreground" = "$text"
"panel.foreground.dim" = "$dim-text"
"panel.current.background" = "$current-background"
"panel.current.foreground" = "$text"
"panel.current.foreground.dim" = "$dim-text"
"panel.hovered.background" = "#4C5052"
"panel.hovered.active.background" = "#515151"
"panel.hovered.foreground" = "$text"
"panel.hovered.foreground.dim" = "$dim-text"

"status.background" = "$secondary-background"
"status.foreground" = "$text"
"status.modal.normal.background" = "#4A6DA7"
"status.modal.normal.foreground" = "$white"
"status.modal.insert.background" = "#629755"
"status.modal.insert.foreground" = "$primary-background"
"status.modal.visual.background" = "$orange"
"status.modal.visual.foreground" = "$primary-background"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$primary-background"

"markdown.blockquote" = "#808080"

"terminal.cursor" = "$text"
"terminal.foreground" = "$text"
"terminal.background" = "$primary-background"
"terminal.white" = "#A9B7C6"
"terminal.black" = "#2B2B2B"
"terminal.red" = "#FF6B68"
"terminal.blue" = "#6897BB"
"terminal.green" = "#6A8759"
"terminal.yellow" = "#FFC66D"
"terminal.cyan" = "#56B6C2"
"terminal.magenta" = "#9876AA"
"terminal.bright_white" = "#D0D0D0"
"terminal.bright_red" = "#FF8785"
"terminal.bright_blue" = "#7EAAC7"
"terminal.bright_green" = "#85A768"
"terminal.bright_yellow" = "#FFDA8A"
"terminal.bright_cyan" = "#6FD0D3"
"terminal.bright_magenta" = "#B09ACF"
"terminal.bright_black" = "#555555"
